const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
module.exports=async function checkCare(win,mouse,waitFor,pause) {
  const js=code=>win.webContents.executeJavaScript(code);
  assert.ok(await js(`document.querySelector('#feed-pet').nextElementSibling===toyButton && document.querySelectorAll('#pet-vitals meter').length===4`),'Toy follows food; four SVG status meters');
  await js(`closeTools();hovering=false;foods.splice(0).forEach(f=>f.element.remove());queuedActions.length=0;pendingWaste=null;overrideTime=0;restPhase='none';x=200;y=250;toyButton.click()`);
  const point=await js(`({x:Math.round(x+petWidth/2+55),y:Math.round(y+petWidth*.8)})`);
  await mouse({type:'mouseMove',...point});await pause(80);
  assert.ok(await js(`placingToy && Math.abs(x-200)<1`),'Pet waits for toy release');
  await mouse({type:'mouseDown',button:'left',clickCount:1,...point});
  await mouse({type:'mouseUp',button:'left',clickCount:1,...point});
  await mouse({type:'mouseMove',x:700,y:20});
  assert.ok(await js(`playingToy&&!placingToy&&Math.abs(toyX-${point.x})<1`),'Toy stays where released after cursor moves away');
  await js(`openTools();hovering=true;document.querySelector('#clean-pet').focus()`);
  await waitFor(win,`toyCursor.classList.contains('caught')`);
  assert.ok(await js(`action==='wiggle'&&stamina<100`),'Pet reaches toy despite focused toolbar, and playing uses energy');
  await mouse({type:'mouseMove',...point});
  await mouse({type:'mouseDown',button:'left',clickCount:1,...point});
  await mouse({type:'mouseMove',x:point.x+45,y:point.y,button:'left',modifiers:['leftButtonDown']});
  await mouse({type:'mouseUp',button:'left',clickCount:1,x:point.x+45,y:point.y});
  await waitFor(win,`!placingToy&&Math.abs(toyX-${point.x+45})<1&&toyCursor.classList.contains('caught')`);
  await js(`toyPlayRemaining=.15`);
  await waitFor(win,`!playingToy&&toyCursor.hidden`);
  await js(`toggleToy();startFoodPlacement()`);
  assert.ok(await js(`placingFood&&!playingToy&&toyCursor.hidden`),'Feed cancels toy placement');
  await js(`cancelFoodPlacement();toggleToy()`);
  await win.webContents.debugger.sendCommand('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});
  assert.ok(await js(`!playingToy&&!placingToy`),'Esc clears toy');
  console.log('PASS toy release, fixed target, toolbar priority, redrag, energy, completion and cancellation');
  await js(`renderState({petId:selectedId,hunger:10,mood:12,weight:35,growth:0});openTools();syncVitals()`);
  assert.ok(await js(`petWidth<55&&pet.classList.contains('hungry')&&moodBadge.querySelector('svg')&&getComputedStyle(moodBadge).opacity==='1'&&document.querySelector('#hunger-meter').value===10&&document.querySelector('#happiness-meter').value===12&&document.querySelector('#energy-meter').value<35`),'Tiny baby size, obvious hunger during hover, fullness and happiness values');
  await js(`makeWaste('poop');syncVitals()`);
  assert.equal(await js(`document.querySelector('#cleanliness-meter').value`),85);
  await js(`cleanWaste()`);
  await waitFor(win,`document.querySelector('#cleanliness-meter').value===100`);
  await js(`renderState({petId:selectedId,hunger:80,mood:70,weight:90,growth:100});openTools()`);
  assert.ok(await js(`petWidth===manifest.displaySize&&bodyWidth>1.1`),'Feeding growth and rounder shape affect sprite');
  await pause(100);
  const rect=await js(`(()=>{const p=pet.getBoundingClientRect(),t=petTools.getBoundingClientRect();return {x:Math.floor(t.left-8),y:Math.floor(t.top-8),width:Math.ceil(t.width+16),height:Math.ceil(p.bottom-t.top+16)}})()`);
  fs.writeFileSync(path.join(__dirname,'../blender/vitals-preview.png'),(await win.webContents.capturePage(rect)).toPNG());
  await mouse({type:'mouseMove',x:700,y:20});
  await js(`renderState({petId:selectedId,hunger:80,mood:70,weight:35,growth:0});closeTools();hovering=false;document.activeElement.blur();x=200;y=250;overrideTime=0;mode={action:'walk',duration:10,weight:1,speedScale:1};modeTimer=10;direction=1`);
  const before=await js(`({x,phase:gaitPhase,stride:manifest.animations.walk.stride*petWidth/256*bodyWidth})`);
  await pause(180);
  const after=await js(`({x,phase:gaitPhase})`),expected=(before.phase+(after.x-before.x)/before.stride)%1;
  assert.ok(Math.abs(expected-after.phase)<.025,'Gait follows actual displacement');
  console.log('PASS baby size, growth, obvious hunger, live vitals, cleaning recovery and dog gait');
  const {PetStateManager}=require('../dist/main/petState.js');
  const state=new PetStateManager();
  assert.equal(state.getState().growth,0);assert.equal(state.getState().weight,35);
  for(let i=0;i<80;i++)state.feed();
  assert.equal(state.getState().growth,100);assert.equal(state.getState().weight,100);
  for(let i=0;i<240;i++)state.decay();
  assert.equal(state.getState().growth,100);assert.equal(state.getState().weight,0);
  state.select('rabbit');assert.equal(state.getState().growth,0);
  const restored=new PetStateManager();restored.restore(JSON.parse(JSON.stringify(state.serialize())));
  assert.equal(restored.getState().petId,'rabbit');assert.equal(restored.select('dog').growth,100);assert.equal(restored.getState().weight,0);
  restored.restore({active:'cat',pets:[{petId:'cat',weight:999,growth:-30,mood:'bad',hunger:null}]});
  assert.equal(restored.getState().weight,100);assert.equal(restored.getState().growth,0);assert.equal(restored.getState().mood,70);
  console.log('PASS growth, feeding and starving bounds, independent pet progress and save/restore');
};
